<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [2]:
import numpy as np 

## Exercise 1 (Total recall): 

|**Term**| **Brief description**| 
|:---    | :--- |
| Subsetting | To select a particular data in a list or an array. | 
| Indexing | To select one specific element that we want. |
| Slicing | To select a range of elements. |
| Masking | _Kills off all the False data, and the code generated will only be the True data, set by a condition._ |

## Exercise 2 (Show me the 'odd' letters:)

In [36]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

#calling the first column 
np_array_2d [:,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [39]:
# converting to int
first_column_int = np_array_2d [:,0].astype(int)
first_column_int

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [40]:
# getting remainders
getting_remainder = first_column_int % 2
getting_remainder

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [42]:
#creating a mask
my_mask = getting_remainder > 0 
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [57]:
np_array_2d [my_mask, 1]
print (np_array_2d [my_mask, 1])

['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [73]:
#defining the array given
data = [[66, 50, 57, -1, -1],
  [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

# Convert to NumPy array
np_2d_array = np.array(data)

In [76]:
np_2d_array [np_2d_array < 50] = -1
np_2d_array [np_2d_array > 50] = 1
np_2d_array [np_2d_array == 50] = 0
print (np_2d_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
