<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [21]:
import numpy as np

# 1 Python Lists, Numpy Arrays & Dictionaries

In [17]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [27]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [14]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

Have the same data, but stored differently. 

Need 3 different ways because we can data in different ways, whichever feels more comfortable.

Nothing will happen if we just run the stored data. We need to access it (see below):

## 1.2 Accessing data from a list (or array)

Python is a zero-indexed language, meaning it starts counting at 0. So if you want to access a particular element in the list (or array), you need to specify the relevant index starting from zero. 

Let's access the data stored in the Python Lists examples above: 

In [5]:
py_super_names [0]

'Black Widow'

In [25]:
py_super_names[1]

'Iron Man'

In [32]:
np_real_names [1]

np.str_('Tony Stark')

In [31]:
py_super_names[-1]      # Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [34]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [37]:
superhero_info["Peter Parker"] = "Spider Man"

In [38]:
superhero_info

{'Natasha Romanoff': 'Black Widow',
 'Tony Stark': 'Iron Man',
 'Stephen Strange': 'Doctor Strange',
 'Peter Parker': 'Spider Man'}

Whenever you want the data (values) out, just give the key (the real names in this case). KEYS COME BEFORE VALUES!!

In [39]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange', 'Peter Parker'])

In [40]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange', 'Spider Man'])

## 1.4 Higher dimensional lists

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [ ]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

Both have same information, but are arranged in different manners. 

In [41]:
superhero_info = {
    "Natasha Romanoff": "Marvel",
    "Tony Stark": "Marvel",
    "Stephen Strange": "Marvel",
    "Diana Prince": "DC"
}

# 2 Lists vs. Arrays

In [42]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

With this function, we can convert int to float, lists to a numpy array. 

Remember to run codes, we can type out the first few alphabets then press Tab then select from the lists (kind of a shortcut).

In [43]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [44]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

We get the same data but it is listed in the form of an array. 

## 2.1 Size

Most of the time, we want to know the size of something. So we use the len() function. 

In [45]:
len(py_list_2d)

10

In [46]:
len(np_array_2d)

10

Though we have 20 elements, the code ran gives us 10 only. This is because the code will only give us the 1st dimention in a multidimensional list. 

Over here we have 10 rows and 2 colums. So len() will always give us the FIRST ROW ONLY.

But what if one of the data set has 3 colums instead like now: 

In [48]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J", "HEYYYYYYYY"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

Arrays are more strict.

But this error won't occur for lists, as lists allows for different type, ints, strs all mixed up also can: 

In [49]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J", "HEYYYYYYYY"]]

py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J', 'HEYYYYYYYY']]

In [50]:
'hahaha'.upper()

'HAHAHA'

In [47]:
np_array_2d.shape

(10, 2)

The difference between the two is that one has a bracket and the other does not. 

This is because shape is an attribute, and thus will not have e.g 'shape()'. 

## 2.2 Arrays are fussy about type

In [51]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

### Lists

In [52]:
py_list

[1, 1.5, 'A']

### Arrays

In [53]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [54]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

### Lists (addition)

In [56]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

This will not work because we are adding a list plus a number. It will only work if we adds two or more lists tgt. Like this: 

In [57]:
py_list + [10]

[1, 2, 3, 4, 5, 10]

### Lists (multiplication)

In [62]:
[1,2] * 10

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

Takes the whole list and slaps it tgt. Changed the initial list of 6 numbers to only 2 numbers if not the list generated will be too long and takes up lots of space. 

### Lists (squaring)

In [63]:
[1,2] ** 10

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Arrays (addition)

In [55]:
np_array + 10

array([11, 12, 13, 14, 15])

### Arrays (multiplication)

In [59]:
np_array * 10

array([10, 20, 30, 40, 50])

### Arrays (squaring)

In [66]:
np_array ** 2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [67]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [73]:
py_list == 3     # Works, but what IS the question?

                 # But it is pretty suspicious in terms of the answer we get, so maybe don't use this haha

                 # When it comes to mathematical operations, just use arrays instead to make life easier!!

False

In [70]:
np_array == 3  

array([False, False,  True, False, False])

In [71]:
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [74]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [75]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function

1

We expected 3 numbers but we only see '1' because Jupyter will generate the last result in this three code commands by default. 

If we want to see all, we need to print all three codes.

In [78]:
print(sum(py_list))    
print(max(py_list))     
print(min(py_list))     

15
5
1


### What are the differences between these two?

In [84]:
%timeit sum(np_array)

2.42 μs ± 59.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [83]:
%timeit np_array.sum()

3.45 μs ± 65.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


One is a Python function and the other is a Numpy function. 

Just shows the comparison between the codes generated. 

In [77]:
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)