<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [4]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
#x = np_array

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [9]:
x[2]              # Basic, just gives index 2. 

'c3'

In [8]:
x[2:4]            # Gives 4-2=2 elements. The first element generated will be the first index so in this case, index 2 = c3. 

['c3', 'd4']

In [7]:
x[2:8:2]          # Gives every other (alternate) of 8-2=6 elements

['c3', 'e5', 'g7']

In [11]:
x[:8:2]           # Starts right at the start so 8-0=8 elements, then selects for every other (alternate) elements. 

['a1', 'c3', 'e5', 'g7']

In [14]:
x[::-1]            # Simply reverses the entire list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [17]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3        # Asking a qn here, what numbers are greater than 3. 
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

### 'AND' / '&' example for addition:

In [19]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = (np_array > 3) & (np_array < 8)
my_mask

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [21]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = (np_array > 3) & (np_array < 8)
np_array [my_mask]         # So here we kill off all the Falses, and the code generated will only be the True data. 

array([4, 5, 6, 7])

We can invert by adding a ~ and this will give everything that was not inside the question asked: 

In [10]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = (np_array > 3) & (np_array < 8)    
np_array [~my_mask]                          # So here we kill off all the TRUES, and the code generated will only be the FALSES data. 

array([ 1,  2,  3,  8,  9, 10])

In [11]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3 & np_array < 8                  # MUST ALWAYS USE THE BRACKETS, IF NOT WILL MESS THINGS UP
np_array [my_mask]             

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
my_mask.sum()

np.int64(4)

### 'OR' / '|' (which will show something if either mask is true):

In [13]:
np_array[(np_array < 3) | (np_array > 8)]          # '|' means 'OR'

array([ 1,  2,  9, 10])

Cannot use 'or' here, needs to use | 

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [27]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [30]:
py_list_2d[3]

[4, 'D']

In [31]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

How do we only get 'D' of index 3? Here is how: 

In [40]:
py_list_2d[3][1]         # Needs to split   

'D'

In [39]:
np_array_2d[3,1]          # Can just add , and it will work

np.str_('D')

## 1.4 Growing lists

In [14]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [17]:
%%timeit
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

565 ns ± 11.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
%%timeit
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

499 ns ± 8.19 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
%%timeit
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

268 ns ± 5.78 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


If you are wondering, there are differences between these three versions. Their execution speeds are different; the version with **append()** runs about 1.5 times faster than the rest!

In [22]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [23]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [24]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

Extend joins the list together, while append just puts the element at the end. 

To put elements at the start: 

In [26]:
x=[1, 2, 3]
x = [0] + x
x

[0, 1, 2, 3]

In [32]:
x=[1, 2, 3]
x.insert(0,"0")   # Green zero is the index (i.e. refers to 1), red 0 is the thing we want to insert, 
                  # and this will be inserted to in front of the first element though it is after the comma.

x

['0', 1, 2, 3]

In [31]:
x=[1, 2, 3]
x.insert(5,"0")    # System does not complain even if there is no fifth index here. Will just insert red 0 at the end.
x

[1, 2, 3, '0']

# Some loose ends

## 1.5 Tuples

In [38]:
a=[1, 2, 3]     # This is a list according to python because it has [] brackets

In [39]:
aa=(1, 2, 3)     # Define tuple

Tuples are similar to lists, except they use ( ) and cannot be changed after creation (i.e., they are immutable).

In [48]:
a=[1, 2, 3]  
a [0] = 1234      #a[0] is accessing the data. Wants to replace the first index (which is 1) to 1234.
a

[1234, 2, 3]

In [49]:
aa=(1, 2, 3)  
aa[0]=1234       #aa[0] is accessing the data. But tuple does not allow it unlike lists.
aa

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [55]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [56]:
print(f'{x=},{y=},{z=}')

x=[1, 2, 3],y=[1, 2, 3],z=[1, 2, 3]


In [57]:
y[0] = 1234

In [58]:
print(f'{x=},{y=},{z=}')

x=[1234, 2, 3],y=[1234, 2, 3],z=[1234, 2, 3]


Here we can see once we change one variable, we change of all of them regardless if its x y or z. 

The correct way to do this is as follows:

In [70]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

Note: At this stage, you only have to know that you must use copy() to be safe; you do not have to understand why. However, if you want to, please refer to the discussion on mutable and immutable objects.

In [71]:
y[0] = 1234

In [72]:
print(f'{x=},{y=},{z=}')

x=[1, 2, 3],y=[1234, 2, 3],z=[1, 2, 3]


Notice how when we use the copy() function, it does not apply to all x y and z unlike the example at the start of this subtopic.

copy() will ensure that the index we change is pertaining to y only, and won't change for x or z, at least for this example. 

## Footnotes

To get a 3D array: 

In [43]:
x = [[[1,2],[3,4]],[[2,2],[3,4]],[[5,6],[7,8]]]     # This is a 3D list

x [0][1][1]                                         # Calling 0 is for the first list
                                                    # Calling the first 1 is for the second set of data in the first list (i.e [3,4])
                                                    # calling the second 1 is for the second value in the second set of data in the first list 

4

In [45]:
x = [[[1,2],[3,4]],[[2,2],[3,4]],[[5,6],[7,8]]]
np_x = np.array(x)

np_x [0,1,1]                                        # Getting the same answer but converting it to numpy instead. 

np.int64(4)